import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import * as React from "react";
import { CheckCircle2, Circle, Sparkles, RefreshCw, ExternalLink, X, RotateCcw, Loader2 } from "lucide-react";
import { AdminLayout } from "@/components/admin-layout";
import {
  generateOpportunities,
  listOpportunities,
  markOpportunity,
  getCoachRole,
} from "@/server/admin-prnm-coach.functions";

type Role = "ceo" | "coo" | "cs";
type Opp = {
  id: string;
  role: Role;
  title: string;
  why: string | null;
  impact: "high" | "medium" | "low";
  effort: "quick" | "medium" | "deep";
  action_label: string | null;
  action_route: string | null;
  completed_at: string | null;
  created_at: string;
};

const ROLE_TABS: Array<{ value: Role; label: string; sub: string }> = [
  { value: "ceo", label: "CEO",   sub: "Derek — strategy & growth" },
  { value: "coo", label: "COO",   sub: "Brandon — outreach & ops" },
  { value: "cs",  label: "CS",    sub: "Michelle — replies & follow-ups" },
];

const IMPACT_STYLE: Record<Opp["impact"], string> = {
  high:   "bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/20",
  medium: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
  low:    "bg-muted text-muted-foreground border-border",
};
const EFFORT_STYLE: Record<Opp["effort"], string> = {
  quick:  "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
  medium: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20",
  deep:   "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
};

export const Route = createFileRoute("/admin/opportunities")({
  component: OpportunitiesPage,
});

function OpportunitiesPage() {
  const fetchRole = useServerFn(getCoachRole);
  const list = useServerFn(listOpportunities);
  const generate = useServerFn(generateOpportunities);
  const mark = useServerFn(markOpportunity);

  const [activeRole, setActiveRole] = React.useState<Role>("ceo");
  const [items, setItems] = React.useState<Opp[]>([]);
  const [loading, setLoading] = React.useState(false);
  const [generating, setGenerating] = React.useState(false);
  const [showCompleted, setShowCompleted] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  // Resolve role on mount and load that tab
  React.useEffect(() => {
    (async () => {
      try {
        const r = await fetchRole({ data: {} });
        setActiveRole(r.role);
      } catch { /* default ceo */ }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const refresh = React.useCallback(async (role: Role) => {
    setLoading(true);
    setError(null);
    try {
      const r = await list({ data: { role, includeCompleted: true } });
      if (r.ok) setItems(r.items as Opp[]);
      else setError(r.error);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load");
    } finally {
      setLoading(false);
    }
  }, [list]);

  React.useEffect(() => { void refresh(activeRole); }, [activeRole, refresh]);

  async function handleGenerate() {
    setGenerating(true);
    setError(null);
    try {
      const r = await generate({ data: { role: activeRole } });
      if (!r.ok) setError(r.error);
      else await refresh(activeRole);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Generation failed");
    } finally {
      setGenerating(false);
    }
  }

  async function toggleDone(opp: Opp) {
    const next = opp.completed_at ? "reopen" : "complete";
    // optimistic
    setItems((prev) =>
      prev.map((x) => x.id === opp.id ? { ...x, completed_at: next === "complete" ? new Date().toISOString() : null } : x)
    );
    try { await mark({ data: { id: opp.id, action: next } }); }
    catch { void refresh(activeRole); }
  }

  async function dismiss(opp: Opp) {
    setItems((prev) => prev.filter((x) => x.id !== opp.id));
    try { await mark({ data: { id: opp.id, action: "dismiss" } }); }
    catch { void refresh(activeRole); }
  }

  const open = items.filter((i) => !i.completed_at);
  const done = items.filter((i) => !!i.completed_at);

  return (
    <AdminLayout>
      <div className="max-w-4xl mx-auto px-4 py-6">
        <div className="flex items-start justify-between gap-4 mb-4 flex-wrap">
          <div>
            <h1 className="text-2xl font-semibold flex items-center gap-2">
              <Sparkles className="h-6 w-6 text-primary" /> Today's opportunities
            </h1>
            <p className="text-sm text-muted-foreground mt-1">
              High-impact actions tailored to your role. Generated by the PRNM Coach from live platform data.
            </p>
          </div>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="inline-flex items-center gap-2 rounded-md bg-primary text-primary-foreground px-4 py-2 text-sm font-medium disabled:opacity-50"
          >
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
            {generating ? "Researching live data…" : open.length > 0 ? "Regenerate list" : "Generate priorities"}
          </button>
        </div>

        <div className="flex gap-1 border-b mb-4 overflow-x-auto">
          {ROLE_TABS.map((t) => (
            <button
              key={t.value}
              onClick={() => setActiveRole(t.value)}
              className={
                activeRole === t.value
                  ? "px-4 py-2 text-sm font-medium border-b-2 border-primary text-foreground"
                  : "px-4 py-2 text-sm text-muted-foreground hover:text-foreground border-b-2 border-transparent"
              }
            >
              {t.label}
              <span className="ml-2 text-xs opacity-70">{t.sub}</span>
            </button>
          ))}
        </div>

        {error && (
          <div className="rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-2 text-sm text-destructive mb-4">
            {error}
          </div>
        )}

        {loading && items.length === 0 && (
          <div className="text-sm text-muted-foreground py-12 text-center">Loading…</div>
        )}

        {!loading && open.length === 0 && done.length === 0 && (
          <div className="rounded-lg border border-dashed py-12 text-center space-y-2">
            <p className="text-sm text-muted-foreground">No opportunities yet for {ROLE_TABS.find(t => t.value === activeRole)?.label}.</p>
            <p className="text-xs text-muted-foreground">Click <strong>Generate priorities</strong> to have the Coach research live data.</p>
          </div>
        )}

        {open.length > 0 && (
          <div className="space-y-3">
            <h2 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
              Open · {open.length}
            </h2>
            {open.map((opp) => (
              <OppCard key={opp.id} opp={opp} onToggle={toggleDone} onDismiss={dismiss} />
            ))}
          </div>
        )}

        {done.length > 0 && (
          <div className="mt-8 space-y-3">
            <button
              onClick={() => setShowCompleted((v) => !v)}
              className="text-sm font-semibold text-muted-foreground uppercase tracking-wide hover:text-foreground flex items-center gap-2"
            >
              Done · {done.length} {showCompleted ? "▾" : "▸"}
            </button>
            {showCompleted && done.map((opp) => (
              <OppCard key={opp.id} opp={opp} onToggle={toggleDone} onDismiss={dismiss} />
            ))}
          </div>
        )}
      </div>
    </AdminLayout>
  );
}

function OppCard({
  opp, onToggle, onDismiss,
}: { opp: Opp; onToggle: (o: Opp) => void; onDismiss: (o: Opp) => void }) {
  const done = !!opp.completed_at;
  return (
    <div
      className={
        done
          ? "rounded-lg border bg-muted/40 px-4 py-3 flex gap-3 opacity-70"
          : "rounded-lg border bg-card px-4 py-3 flex gap-3 hover:border-primary/40 transition-colors"
      }
    >
      <button
        onClick={() => onToggle(opp)}
        className="mt-0.5 shrink-0"
        title={done ? "Mark as not done" : "Mark as done"}
      >
        {done
          ? <CheckCircle2 className="h-5 w-5 text-emerald-600" />
          : <Circle className="h-5 w-5 text-muted-foreground hover:text-primary" />}
      </button>
      <div className="flex-1 min-w-0">
        <div className="flex items-start justify-between gap-2">
          <h3 className={done ? "font-medium line-through" : "font-medium"}>{opp.title}</h3>
          <div className="flex items-center gap-1 shrink-0">
            <span className={`text-[10px] uppercase tracking-wide font-semibold px-1.5 py-0.5 rounded border ${IMPACT_STYLE[opp.impact]}`}>
              {opp.impact}
            </span>
            <span className={`text-[10px] uppercase tracking-wide font-semibold px-1.5 py-0.5 rounded border ${EFFORT_STYLE[opp.effort]}`}>
              {opp.effort}
            </span>
          </div>
        </div>
        {opp.why && <p className="text-sm text-muted-foreground mt-1">{opp.why}</p>}
        <div className="flex items-center gap-2 mt-2">
          {opp.action_route && (
            <a
              href={opp.action_route}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 rounded-md bg-primary/10 hover:bg-primary/20 text-primary px-2.5 py-1 text-xs font-medium"
            >
              <ExternalLink className="h-3 w-3" />
              {opp.action_label || "Open tool"}
            </a>
          )}
          {done ? (
            <button
              onClick={() => onToggle(opp)}
              className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"
            >
              <RotateCcw className="h-3 w-3" /> Reopen
            </button>
          ) : (
            <button
              onClick={() => onDismiss(opp)}
              className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"
              title="Hide this from the list"
            >
              <X className="h-3 w-3" /> Dismiss
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
