#!/usr/bin/env bun
/**
 * Backfill content_pages by Firecrawling every /p/{slug} URL on the live
 * Sharetribe site and writing the cleaned markdown into Supabase. Same pattern
 * as backfill-heroes.ts.
 *
 * USAGE
 *   bun run scripts/backfill-content.ts                    # all URLs
 *   bun run scripts/backfill-content.ts --dry              # don't write to DB
 *   bun run scripts/backfill-content.ts --limit=50         # first 50 URLs
 *   bun run scripts/backfill-content.ts --slugs=foo,bar    # specific slugs
 *   bun run scripts/backfill-content.ts --priority=tier1   # tier1 (top 16) only
 *   bun run scripts/backfill-content.ts --force            # re-fetch even if row exists
 *
 * ENV
 *   FIRECRAWL_API_KEY
 *   SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 *
 * INPUT
 *   url_mapping.csv at the repo root (generated by migration-plan/gen_url_mapping.py)
 *   Only rows with action=BUILD_NEW and template_type starting with anything except pp_, listing, host_profile, amenity, amenity_hub
 */
import Firecrawl from "@mendable/firecrawl-js";
import { createClient } from "@supabase/supabase-js";
import { readFileSync, writeFileSync } from "node:fs";

const FIRECRAWL_API_KEY = process.env.FIRECRAWL_API_KEY!;
const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
if (!FIRECRAWL_API_KEY || !SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("Missing env: FIRECRAWL_API_KEY, SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const client = new Firecrawl({ apiKey: FIRECRAWL_API_KEY });
const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ---------- Slug normalization (per migration-plan/03-slug-normalization.md) ----------

// Hand-curated map for ugly mashed slugs that the heuristic in
// gen_url_mapping.py can't reliably split (e.g. multi-word cities).
const SLUG_OVERRIDES: Record<string, string> = {
  losangeles: "los-angeles",
  newyork: "new-york",
  lasvegas: "las-vegas",
  sanantonio: "san-antonio",
  sandiego: "san-diego",
  sanfrancisco: "san-francisco",
  sanjose: "san-jose",
  katytexas: "katy-texas",
  sacramentobestprivatepools: "sacramento-best-private-pools",
  privatepoolrentalssandiego: "private-pool-rentals-san-diego",
  howtoturnyourbackyardpoolintoabusinessasset:
    "how-to-turn-your-backyard-pool-into-a-business-asset",
  privatepoolpartyriversideca: "private-pool-party-riverside-ca",
};

// Host-acquisition duplicate pairs (per check_host_duplicates.py).
// Map from non-canonical slug -> canonical slug. The non-canonical becomes a
// legacy_slug on the canonical row.
const DUPLICATE_PAIRS: Record<string, string> = {
  "become-a-pool-host-chandler-arizona": "become-a-swimming-pool-host-chandler-az",
  "become-a-pool-host-escondido-california": "become-a-swimming-pool-host-escondido-ca",
  "become-a-pool-host-oceanside-california": "become-a-swimming-pool-host-oceanside-ca",
  "become-a-pool-host-surprise-arizona": "become-a-swimming-pool-host-surprise-az",
  "become-a-pool-host-tempe-arizona": "become-a-swimming-pool-host-tempe-az",
  "become-a-pool-host-tucson-arizona": "become-a-swimming-pool-host-tucson-az",
  "become-a-swimming-pool-host-albuquerque-new-mexico":
    "become-a-swimming-pool-host-albuquerque-nm",
  "become-a-swimming-pool-host-hilo-hawaii": "become-a-swimming-pool-host-hilo-hi",
  "become-a-swimming-pool-host-idaho-falls-idaho":
    "become-a-swimming-pool-host-idaho-falls-id",
  "become-a-swimming-pool-host-meridian-idaho": "become-a-swimming-pool-host-meridian-id",
};

function normalizeSlug(rawSlug: string): { canonical: string; legacy: string[] } {
  const legacy: string[] = [];
  let canonical = rawSlug;

  if (DUPLICATE_PAIRS[rawSlug]) {
    canonical = DUPLICATE_PAIRS[rawSlug];
    legacy.push(rawSlug);
  } else if (SLUG_OVERRIDES[rawSlug]) {
    canonical = SLUG_OVERRIDES[rawSlug];
    legacy.push(rawSlug);
  }

  return { canonical, legacy };
}

// ---------- Template type classification (mirror gen_url_mapping.py) ----------

const MONEY_PAGES = new Set([
  "all-locations", "why-hosts-are-leaving-swimply",
  "swimply-alternative-vs-pool-rental-near-me",
  "about", "investors", "howitworksforguests", "hosting", "make-money",
  "los-angeles", "new-york", "las-vegas-search-page", "katy-texas",
  "sacramento-best-private-pools", "private-pool-rentals-san-diego", "riverside",
]);

function classifyTemplateType(canonicalSlug: string): {
  template_type: string;
  language: "en" | "es";
} {
  if (canonicalSlug.startsWith("become-a-pool-host-") || canonicalSlug.startsWith("become-a-swimming-pool-host-")) {
    return { template_type: "host_acquisition_city", language: "en" };
  }
  if (canonicalSlug.startsWith("guide-to-") && canonicalSlug.includes("pool-rental")) {
    return { template_type: "event_city_guide", language: "en" };
  }
  if (canonicalSlug.startsWith("conviertete-en-anfitrion-de-piscina")) {
    return { template_type: "spanish_host_acquisition", language: "es" };
  }
  if (canonicalSlug.startsWith("aprende-")) {
    return { template_type: "spanish_resource", language: "es" };
  }
  if (canonicalSlug.startsWith("host-advocacy")) {
    return { template_type: "host_advocacy", language: "en" };
  }
  if (canonicalSlug.startsWith("elearning-academy-")) {
    return { template_type: "academy_article", language: "en" };
  }
  if (canonicalSlug.endsWith("-pool-host-advocacy-guide")) {
    return { template_type: "state_advocacy_guide", language: "en" };
  }
  if (MONEY_PAGES.has(canonicalSlug)) {
    return { template_type: "money_page", language: "en" };
  }
  return { template_type: "resource_article", language: "en" };
}

// ---------- Tier priority for --priority=tier1 flag ----------

const TIER1_SLUGS = new Set([
  "all-locations", "newyork", "privatepoolrentalssandiego", "riverside",
  "las-vegas-search-page", "american-cities-with-pools",
  "rent-a-swimming-pool-fort-greene-ny",
  "top-20-romantic-us-retreats-with-pools",
  "pool-rental-tax-write-offs-your-missing-out-on", "host-advocacy-texas",
  "best-poolside-beers", "hosting", "sacramentobestprivatepools",
  "howtoturnyourbackyardpoolintoabusinessasset", "privatepoolpartyriversideca",
  "losangeles", "katytexas", "swimply-alternative-vs-pool-rental-near-me",
  "why-hosts-are-leaving-swimply", "make-money", "about", "investors",
  "howitworksforguests",
]);

// ---------- Firecrawl extraction ----------

interface ExtractedPage {
  title: string;
  description: string | null;
  cover_image_url: string | null;
  content_markdown: string;
  published_at: string | null;
  word_count: number;
}

async function extractPage(url: string): Promise<ExtractedPage> {
  const res: any = await client.scrape(url, {
    formats: ["markdown", "rawHtml"],
    onlyMainContent: true,
    waitFor: 1500,
  });

  const md: string = res.markdown ?? res.data?.markdown ?? "";
  const meta = res.metadata ?? res.data?.metadata ?? {};
  const html: string = res.rawHtml ?? res.data?.rawHtml ?? "";

  // Title — prefer og:title, else <title>, else first H1
  const title =
    (meta.ogTitle as string) ??
    (meta.title as string) ??
    extractFirstH1(md) ??
    "(untitled)";

  // Description — prefer meta description, else first paragraph
  const description =
    (meta.description as string) ??
    (meta.ogDescription as string) ??
    extractFirstParagraph(md);

  // Cover image — prefer og:image, then first <img> in markdown
  const cover_image_url =
    (meta.ogImage as string) ??
    extractFirstImage(md) ??
    null;

  // Strip Sharetribe nav/header/footer chrome from markdown if onlyMainContent missed it
  const cleaned = stripSharetribeChrome(md);

  // Word count of cleaned content
  const word_count = cleaned.trim().split(/\s+/).filter(Boolean).length;

  // published_at — try article:published_time, else null
  const published_at =
    (meta.publishedTime as string) ??
    (meta["article:published_time"] as string) ??
    null;

  return {
    title: title.trim(),
    description: description?.trim() || null,
    cover_image_url,
    content_markdown: cleaned,
    published_at,
    word_count,
  };
}

function extractFirstH1(md: string): string | null {
  const m = md.match(/^#\s+(.+)$/m);
  return m ? m[1].replace(/\[(.+?)\]\(.+?\)/g, "$1").trim() : null;
}

function extractFirstParagraph(md: string): string | null {
  // Find the first non-heading, non-empty line
  const lines = md.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("#")) continue;
    if (trimmed.startsWith("![")) continue; // image
    if (trimmed.startsWith(">")) continue; // blockquote
    if (trimmed.length < 30) continue; // too short
    return trimmed.slice(0, 300);
  }
  return null;
}

function extractFirstImage(md: string): string | null {
  const m = md.match(/!\[.*?\]\((https?:\/\/[^)]+)\)/);
  return m ? m[1] : null;
}

function stripSharetribeChrome(md: string): string {
  // Common Sharetribe footer/nav phrases that leak into the markdown when
  // onlyMainContent doesn't cleanly catch them. Conservative — only strip
  // confident matches.
  const patterns = [
    /© \d{4} Pool Rental Near Me[\s\S]*$/i,
    /Pool Rental Near Me on (Facebook|Instagram|TikTok)[\s\S]*$/i,
    /Sign up\s*\n\s*Log in[\s\S]*?(?=\n#)/g,
  ];
  let out = md;
  for (const p of patterns) {
    out = out.replace(p, "");
  }
  return out.trim();
}

// ---------- Per-URL processor ----------

interface UrlEntry {
  old_url: string;
  old_path: string;
  raw_slug: string;
  template_type: string;
  language: "en" | "es";
  canonical_slug: string;
  legacy_slugs: string[];
}

function entryFromUrl(url: string): UrlEntry | null {
  try {
    const u = new URL(url);
    if (!u.pathname.startsWith("/p/")) return null;
    const rawSlug = u.pathname.slice(3);
    if (!rawSlug || rawSlug.includes("/")) return null;
    const { canonical, legacy } = normalizeSlug(rawSlug);
    const { template_type, language } = classifyTemplateType(canonical);
    return {
      old_url: url,
      old_path: u.pathname,
      raw_slug: rawSlug,
      template_type,
      language,
      canonical_slug: canonical,
      legacy_slugs: legacy,
    };
  } catch {
    return null;
  }
}

async function processOne(
  entry: UrlEntry,
  opts: { dryRun: boolean; force: boolean }
): Promise<{ status: "ok" | "skipped" | "miss" | "error"; error?: string; word_count?: number }> {
  // Skip if already in content_pages and not --force
  if (!opts.force) {
    const { data: existing } = await sb
      .from("content_pages")
      .select("id")
      .eq("slug", entry.canonical_slug)
      .maybeSingle();
    if (existing) return { status: "skipped" };
  }

  // Crawl
  let extracted: ExtractedPage;
  try {
    extracted = await extractPage(entry.old_url);
  } catch (e) {
    return { status: "error", error: e instanceof Error ? e.message : String(e) };
  }

  if (!extracted.content_markdown || extracted.word_count < 50) {
    return { status: "miss", error: `thin content (${extracted.word_count} words)` };
  }

  if (opts.dryRun) {
    return { status: "ok", word_count: extracted.word_count };
  }

  // Upsert
  const row = {
    slug: entry.canonical_slug,
    template_type: entry.template_type,
    language: entry.language,
    title: extracted.title,
    description: extracted.description,
    content: extracted.content_markdown,
    cover_image_url: extracted.cover_image_url,
    published_at: extracted.published_at,
    legacy_slugs: entry.legacy_slugs,
    is_published: true,
  };
  const { error } = await sb
    .from("content_pages")
    .upsert(row, { onConflict: "slug" });
  if (error) return { status: "error", error: error.message };

  return { status: "ok", word_count: extracted.word_count };
}

// ---------- Inventory loader ----------

function loadInventory(csvPath: string): UrlEntry[] {
  const txt = readFileSync(csvPath, "utf8");
  const lines = txt.split("\n").slice(1).filter(Boolean);
  const entries: UrlEntry[] = [];
  for (const line of lines) {
    // Naive CSV parse — these rows don't contain quoted commas in columns we care about
    const cols = line.split(",");
    const url = cols[0];
    const action = cols[5];
    if (!url || !action) continue;
    if (action !== "BUILD_NEW" && action !== "BUILD_NEW_WITH_REDIRECT") continue;
    const e = entryFromUrl(url);
    if (e) entries.push(e);
  }
  return entries;
}

// ---------- Main ----------

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry");
  const force = args.includes("--force");
  const limit = numberArg(args, "--limit");
  const slugs = csvArg(args, "--slugs");
  const priority = stringArg(args, "--priority");
  const csvPath = stringArg(args, "--csv") ?? "../migration-plan/url_mapping.csv";

  let entries = loadInventory(csvPath);

  // De-dupe by canonical_slug — multiple raw URLs can canonicalize to same slug
  const seen = new Set<string>();
  entries = entries.filter((e) => {
    if (seen.has(e.canonical_slug)) return false;
    seen.add(e.canonical_slug);
    return true;
  });

  if (priority === "tier1") {
    entries = entries.filter((e) => TIER1_SLUGS.has(e.canonical_slug) || TIER1_SLUGS.has(e.raw_slug));
  }
  if (slugs?.length) {
    const set = new Set(slugs);
    entries = entries.filter((e) => set.has(e.canonical_slug) || set.has(e.raw_slug));
  }
  if (limit) entries = entries.slice(0, limit);

  console.log(`Processing ${entries.length} URLs (dryRun=${dryRun}, force=${force})…`);

  const concurrency = 4;
  const results: any[] = [];
  let cursor = 0;
  let done = 0;
  await Promise.all(
    Array.from({ length: concurrency }, async () => {
      while (cursor < entries.length) {
        const e = entries[cursor++];
        const r = await processOne(e, { dryRun, force });
        done++;
        const tag =
          r.status === "ok" ? "✓" : r.status === "skipped" ? "·" : r.status === "miss" ? "—" : "✗";
        const wc = r.word_count ? ` (${r.word_count}w)` : "";
        const err = r.error ? `  ${r.error}` : "";
        console.log(`${tag} [${done}/${entries.length}] ${e.canonical_slug}${wc}${err}`);
        results.push({ ...e, ...r });
        // Polite delay; Firecrawl is ~1 RPS per worker on most plans
        await new Promise((res) => setTimeout(res, 200));
      }
    })
  );

  // Summary
  const summary = results.reduce<Record<string, number>>((acc, r) => {
    acc[r.status] = (acc[r.status] || 0) + 1;
    return acc;
  }, {});
  console.log("\nSummary:", summary);

  // Failure CSV
  const failures = results.filter((r) => r.status === "error" || r.status === "miss");
  if (failures.length) {
    const csv =
      "canonical_slug,old_url,status,error\n" +
      failures
        .map(
          (r) =>
            `${r.canonical_slug},${r.old_url},${r.status},${JSON.stringify(r.error ?? "")}`
        )
        .join("\n");
    writeFileSync("/tmp/content-backfill-failures.csv", csv);
    console.log(`\nWrote /tmp/content-backfill-failures.csv (${failures.length} rows)`);
  }
}

function numberArg(args: string[], flag: string): number | undefined {
  const a = args.find((x) => x.startsWith(`${flag}=`));
  return a ? Number(a.split("=")[1]) : undefined;
}
function stringArg(args: string[], flag: string): string | undefined {
  const a = args.find((x) => x.startsWith(`${flag}=`));
  return a ? a.split("=")[1] : undefined;
}
function csvArg(args: string[], flag: string): string[] | undefined {
  const s = stringArg(args, flag);
  return s ? s.split(",") : undefined;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
