/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostToolsIndexRouteImport } from './routes/host-tools.index'
import { Route as HelpCenterIndexRouteImport } from './routes/help-center.index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as VerifyUidRouteImport } from './routes/verify.$uid'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'
import { Route as PoolRentalCityRouteImport } from './routes/pool-rental.$city'
import { Route as PoolRentalLawsCityRouteImport } from './routes/pool-rental-laws.$city'
import { Route as HostToolsSlugRouteImport } from './routes/host-tools.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as AdminLearningRouteImport } from './routes/admin.learning'
import { Route as AdminClickReportRouteImport } from './routes/admin.click-report'
import { Route as AdminCitiesHeroesRouteImport } from './routes/admin.cities-heroes'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AccountLearningRouteImport } from './routes/account.learning'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as HelpCenterCategoryIndexRouteImport } from './routes/help-center.$category.index'
import { Route as LSlugIdRouteImport } from './routes/l.$slug.$id'
import { Route as HelpCenterCategorySlugRouteImport } from './routes/help-center.$category.$slug'
import { Route as ApiPublicTrackCityClickRouteImport } from './routes/api/public/track-city-click'
import { Route as AdminLearningUserIdRouteImport } from './routes/admin.learning.$userId'
import { Route as ApiCertificatesUidPdfRouteImport } from './routes/api/certificates.$uid.pdf'

const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostToolsIndexRoute = HostToolsIndexRouteImport.update({
  id: '/host-tools/',
  path: '/host-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterIndexRoute = HelpCenterIndexRouteImport.update({
  id: '/help-center/',
  path: '/help-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const VerifyUidRoute = VerifyUidRouteImport.update({
  id: '/verify/$uid',
  path: '/verify/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProvidersRoute,
} as any)
const PoolRentalCityRoute = PoolRentalCityRouteImport.update({
  id: '/pool-rental/$city',
  path: '/pool-rental/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolRentalLawsCityRoute = PoolRentalLawsCityRouteImport.update({
  id: '/pool-rental-laws/$city',
  path: '/pool-rental-laws/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const HostToolsSlugRoute = HostToolsSlugRouteImport.update({
  id: '/host-tools/$slug',
  path: '/host-tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLearningRoute = AdminLearningRouteImport.update({
  id: '/admin/learning',
  path: '/admin/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClickReportRoute = AdminClickReportRouteImport.update({
  id: '/admin/click-report',
  path: '/admin/click-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCitiesHeroesRoute = AdminCitiesHeroesRouteImport.update({
  id: '/admin/cities-heroes',
  path: '/admin/cities-heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLearningRoute = AccountLearningRouteImport.update({
  id: '/account/learning',
  path: '/account/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const HelpCenterCategoryIndexRoute = HelpCenterCategoryIndexRouteImport.update({
  id: '/help-center/$category/',
  path: '/help-center/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugIdRoute = LSlugIdRouteImport.update({
  id: '/l/$slug/$id',
  path: '/l/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterCategorySlugRoute = HelpCenterCategorySlugRouteImport.update({
  id: '/help-center/$category/$slug',
  path: '/help-center/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackCityClickRoute = ApiPublicTrackCityClickRouteImport.update({
  id: '/api/public/track-city-click',
  path: '/api/public/track-city-click',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLearningUserIdRoute = AdminLearningUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminLearningRoute,
} as any)
const ApiCertificatesUidPdfRoute = ApiCertificatesUidPdfRouteImport.update({
  id: '/api/certificates/$uid/pdf',
  path: '/api/certificates/$uid/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/providers': typeof ProvidersRouteWithChildren
  '/academy/$slug': typeof AcademySlugRoute
  '/account/learning': typeof AccountLearningRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cities-heroes': typeof AdminCitiesHeroesRoute
  '/admin/click-report': typeof AdminClickReportRoute
  '/admin/learning': typeof AdminLearningRouteWithChildren
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/host-tools/$slug': typeof HostToolsSlugRoute
  '/pool-rental-laws/$city': typeof PoolRentalLawsCityRoute
  '/pool-rental/$city': typeof PoolRentalCityRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/verify/$uid': typeof VerifyUidRoute
  '/academy/': typeof AcademyIndexRoute
  '/help-center/': typeof HelpCenterIndexRoute
  '/host-tools/': typeof HostToolsIndexRoute
  '/admin/learning/$userId': typeof AdminLearningUserIdRoute
  '/api/public/track-city-click': typeof ApiPublicTrackCityClickRoute
  '/help-center/$category/$slug': typeof HelpCenterCategorySlugRoute
  '/l/$slug/$id': typeof LSlugIdRoute
  '/help-center/$category/': typeof HelpCenterCategoryIndexRoute
  '/api/certificates/$uid/pdf': typeof ApiCertificatesUidPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/providers': typeof ProvidersRouteWithChildren
  '/academy/$slug': typeof AcademySlugRoute
  '/account/learning': typeof AccountLearningRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cities-heroes': typeof AdminCitiesHeroesRoute
  '/admin/click-report': typeof AdminClickReportRoute
  '/admin/learning': typeof AdminLearningRouteWithChildren
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/host-tools/$slug': typeof HostToolsSlugRoute
  '/pool-rental-laws/$city': typeof PoolRentalLawsCityRoute
  '/pool-rental/$city': typeof PoolRentalCityRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/verify/$uid': typeof VerifyUidRoute
  '/academy': typeof AcademyIndexRoute
  '/help-center': typeof HelpCenterIndexRoute
  '/host-tools': typeof HostToolsIndexRoute
  '/admin/learning/$userId': typeof AdminLearningUserIdRoute
  '/api/public/track-city-click': typeof ApiPublicTrackCityClickRoute
  '/help-center/$category/$slug': typeof HelpCenterCategorySlugRoute
  '/l/$slug/$id': typeof LSlugIdRoute
  '/help-center/$category': typeof HelpCenterCategoryIndexRoute
  '/api/certificates/$uid/pdf': typeof ApiCertificatesUidPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/providers': typeof ProvidersRouteWithChildren
  '/academy/$slug': typeof AcademySlugRoute
  '/account/learning': typeof AccountLearningRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cities-heroes': typeof AdminCitiesHeroesRoute
  '/admin/click-report': typeof AdminClickReportRoute
  '/admin/learning': typeof AdminLearningRouteWithChildren
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/host-tools/$slug': typeof HostToolsSlugRoute
  '/pool-rental-laws/$city': typeof PoolRentalLawsCityRoute
  '/pool-rental/$city': typeof PoolRentalCityRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/verify/$uid': typeof VerifyUidRoute
  '/academy/': typeof AcademyIndexRoute
  '/help-center/': typeof HelpCenterIndexRoute
  '/host-tools/': typeof HostToolsIndexRoute
  '/admin/learning/$userId': typeof AdminLearningUserIdRoute
  '/api/public/track-city-click': typeof ApiPublicTrackCityClickRoute
  '/help-center/$category/$slug': typeof HelpCenterCategorySlugRoute
  '/l/$slug/$id': typeof LSlugIdRoute
  '/help-center/$category/': typeof HelpCenterCategoryIndexRoute
  '/api/certificates/$uid/pdf': typeof ApiCertificatesUidPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/auth'
    | '/blog'
    | '/providers'
    | '/academy/$slug'
    | '/account/learning'
    | '/admin/blog'
    | '/admin/cities-heroes'
    | '/admin/click-report'
    | '/admin/learning'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/category/$slug'
    | '/host-tools/$slug'
    | '/pool-rental-laws/$city'
    | '/pool-rental/$city'
    | '/providers/$slug'
    | '/verify/$uid'
    | '/academy/'
    | '/help-center/'
    | '/host-tools/'
    | '/admin/learning/$userId'
    | '/api/public/track-city-click'
    | '/help-center/$category/$slug'
    | '/l/$slug/$id'
    | '/help-center/$category/'
    | '/api/certificates/$uid/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/providers'
    | '/academy/$slug'
    | '/account/learning'
    | '/admin/blog'
    | '/admin/cities-heroes'
    | '/admin/click-report'
    | '/admin/learning'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/category/$slug'
    | '/host-tools/$slug'
    | '/pool-rental-laws/$city'
    | '/pool-rental/$city'
    | '/providers/$slug'
    | '/verify/$uid'
    | '/academy'
    | '/help-center'
    | '/host-tools'
    | '/admin/learning/$userId'
    | '/api/public/track-city-click'
    | '/help-center/$category/$slug'
    | '/l/$slug/$id'
    | '/help-center/$category'
    | '/api/certificates/$uid/pdf'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/auth'
    | '/blog'
    | '/providers'
    | '/academy/$slug'
    | '/account/learning'
    | '/admin/blog'
    | '/admin/cities-heroes'
    | '/admin/click-report'
    | '/admin/learning'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/category/$slug'
    | '/host-tools/$slug'
    | '/pool-rental-laws/$city'
    | '/pool-rental/$city'
    | '/providers/$slug'
    | '/verify/$uid'
    | '/academy/'
    | '/help-center/'
    | '/host-tools/'
    | '/admin/learning/$userId'
    | '/api/public/track-city-click'
    | '/help-center/$category/$slug'
    | '/l/$slug/$id'
    | '/help-center/$category/'
    | '/api/certificates/$uid/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ProvidersRoute: typeof ProvidersRouteWithChildren
  AccountLearningRoute: typeof AccountLearningRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCitiesHeroesRoute: typeof AdminCitiesHeroesRoute
  AdminClickReportRoute: typeof AdminClickReportRoute
  AdminLearningRoute: typeof AdminLearningRouteWithChildren
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  CategorySlugRoute: typeof CategorySlugRoute
  HostToolsSlugRoute: typeof HostToolsSlugRoute
  PoolRentalLawsCityRoute: typeof PoolRentalLawsCityRoute
  PoolRentalCityRoute: typeof PoolRentalCityRoute
  VerifyUidRoute: typeof VerifyUidRoute
  HelpCenterIndexRoute: typeof HelpCenterIndexRoute
  HostToolsIndexRoute: typeof HostToolsIndexRoute
  ApiPublicTrackCityClickRoute: typeof ApiPublicTrackCityClickRoute
  HelpCenterCategorySlugRoute: typeof HelpCenterCategorySlugRoute
  LSlugIdRoute: typeof LSlugIdRoute
  HelpCenterCategoryIndexRoute: typeof HelpCenterCategoryIndexRoute
  ApiCertificatesUidPdfRoute: typeof ApiCertificatesUidPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-tools/': {
      id: '/host-tools/'
      path: '/host-tools'
      fullPath: '/host-tools/'
      preLoaderRoute: typeof HostToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center/': {
      id: '/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof HelpCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/verify/$uid': {
      id: '/verify/$uid'
      path: '/verify/$uid'
      fullPath: '/verify/$uid'
      preLoaderRoute: typeof VerifyUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/pool-rental/$city': {
      id: '/pool-rental/$city'
      path: '/pool-rental/$city'
      fullPath: '/pool-rental/$city'
      preLoaderRoute: typeof PoolRentalCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool-rental-laws/$city': {
      id: '/pool-rental-laws/$city'
      path: '/pool-rental-laws/$city'
      fullPath: '/pool-rental-laws/$city'
      preLoaderRoute: typeof PoolRentalLawsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-tools/$slug': {
      id: '/host-tools/$slug'
      path: '/host-tools/$slug'
      fullPath: '/host-tools/$slug'
      preLoaderRoute: typeof HostToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/learning': {
      id: '/admin/learning'
      path: '/admin/learning'
      fullPath: '/admin/learning'
      preLoaderRoute: typeof AdminLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/click-report': {
      id: '/admin/click-report'
      path: '/admin/click-report'
      fullPath: '/admin/click-report'
      preLoaderRoute: typeof AdminClickReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cities-heroes': {
      id: '/admin/cities-heroes'
      path: '/admin/cities-heroes'
      fullPath: '/admin/cities-heroes'
      preLoaderRoute: typeof AdminCitiesHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/learning': {
      id: '/account/learning'
      path: '/account/learning'
      fullPath: '/account/learning'
      preLoaderRoute: typeof AccountLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/help-center/$category/': {
      id: '/help-center/$category/'
      path: '/help-center/$category'
      fullPath: '/help-center/$category/'
      preLoaderRoute: typeof HelpCenterCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug/$id': {
      id: '/l/$slug/$id'
      path: '/l/$slug/$id'
      fullPath: '/l/$slug/$id'
      preLoaderRoute: typeof LSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center/$category/$slug': {
      id: '/help-center/$category/$slug'
      path: '/help-center/$category/$slug'
      fullPath: '/help-center/$category/$slug'
      preLoaderRoute: typeof HelpCenterCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-city-click': {
      id: '/api/public/track-city-click'
      path: '/api/public/track-city-click'
      fullPath: '/api/public/track-city-click'
      preLoaderRoute: typeof ApiPublicTrackCityClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/learning/$userId': {
      id: '/admin/learning/$userId'
      path: '/$userId'
      fullPath: '/admin/learning/$userId'
      preLoaderRoute: typeof AdminLearningUserIdRouteImport
      parentRoute: typeof AdminLearningRoute
    }
    '/api/certificates/$uid/pdf': {
      id: '/api/certificates/$uid/pdf'
      path: '/api/certificates/$uid/pdf'
      fullPath: '/api/certificates/$uid/pdf'
      preLoaderRoute: typeof ApiCertificatesUidPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyRouteChildren {
  AcademySlugRoute: typeof AcademySlugRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademySlugRoute: AcademySlugRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProvidersRouteChildren {
  ProvidersSlugRoute: typeof ProvidersSlugRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersSlugRoute: ProvidersSlugRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface AdminLearningRouteChildren {
  AdminLearningUserIdRoute: typeof AdminLearningUserIdRoute
}

const AdminLearningRouteChildren: AdminLearningRouteChildren = {
  AdminLearningUserIdRoute: AdminLearningUserIdRoute,
}

const AdminLearningRouteWithChildren = AdminLearningRoute._addFileChildren(
  AdminLearningRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ProvidersRoute: ProvidersRouteWithChildren,
  AccountLearningRoute: AccountLearningRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCitiesHeroesRoute: AdminCitiesHeroesRoute,
  AdminClickReportRoute: AdminClickReportRoute,
  AdminLearningRoute: AdminLearningRouteWithChildren,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  CategorySlugRoute: CategorySlugRoute,
  HostToolsSlugRoute: HostToolsSlugRoute,
  PoolRentalLawsCityRoute: PoolRentalLawsCityRoute,
  PoolRentalCityRoute: PoolRentalCityRoute,
  VerifyUidRoute: VerifyUidRoute,
  HelpCenterIndexRoute: HelpCenterIndexRoute,
  HostToolsIndexRoute: HostToolsIndexRoute,
  ApiPublicTrackCityClickRoute: ApiPublicTrackCityClickRoute,
  HelpCenterCategorySlugRoute: HelpCenterCategorySlugRoute,
  LSlugIdRoute: LSlugIdRoute,
  HelpCenterCategoryIndexRoute: HelpCenterCategoryIndexRoute,
  ApiCertificatesUidPdfRoute: ApiCertificatesUidPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
