/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'
import { Route as PoolRentalCityRouteImport } from './routes/pool-rental.$city'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as LSlugIdRouteImport } from './routes/l.$slug.$id'

const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProvidersRoute,
} as any)
const PoolRentalCityRoute = PoolRentalCityRouteImport.update({
  id: '/pool-rental/$city',
  path: '/pool-rental/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const LSlugIdRoute = LSlugIdRouteImport.update({
  id: '/l/$slug/$id',
  path: '/l/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/providers': typeof ProvidersRouteWithChildren
  '/academy/$slug': typeof AcademySlugRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/pool-rental/$city': typeof PoolRentalCityRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/l/$slug/$id': typeof LSlugIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/providers': typeof ProvidersRouteWithChildren
  '/academy/$slug': typeof AcademySlugRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/pool-rental/$city': typeof PoolRentalCityRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/l/$slug/$id': typeof LSlugIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/providers': typeof ProvidersRouteWithChildren
  '/academy/$slug': typeof AcademySlugRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/pool-rental/$city': typeof PoolRentalCityRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/l/$slug/$id': typeof LSlugIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/blog'
    | '/providers'
    | '/academy/$slug'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/category/$slug'
    | '/pool-rental/$city'
    | '/providers/$slug'
    | '/academy/'
    | '/l/$slug/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/providers'
    | '/academy/$slug'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/category/$slug'
    | '/pool-rental/$city'
    | '/providers/$slug'
    | '/academy'
    | '/l/$slug/$id'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/blog'
    | '/providers'
    | '/academy/$slug'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/category/$slug'
    | '/pool-rental/$city'
    | '/providers/$slug'
    | '/academy/'
    | '/l/$slug/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ProvidersRoute: typeof ProvidersRouteWithChildren
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PoolRentalCityRoute: typeof PoolRentalCityRoute
  LSlugIdRoute: typeof LSlugIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/pool-rental/$city': {
      id: '/pool-rental/$city'
      path: '/pool-rental/$city'
      fullPath: '/pool-rental/$city'
      preLoaderRoute: typeof PoolRentalCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/l/$slug/$id': {
      id: '/l/$slug/$id'
      path: '/l/$slug/$id'
      fullPath: '/l/$slug/$id'
      preLoaderRoute: typeof LSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyRouteChildren {
  AcademySlugRoute: typeof AcademySlugRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademySlugRoute: AcademySlugRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProvidersRouteChildren {
  ProvidersSlugRoute: typeof ProvidersSlugRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersSlugRoute: ProvidersSlugRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ProvidersRoute: ProvidersRouteWithChildren,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  CategorySlugRoute: CategorySlugRoute,
  PoolRentalCityRoute: PoolRentalCityRoute,
  LSlugIdRoute: LSlugIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
